name: WebAppTemplateCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-and-test:
    name: Call BuildAndTestAction
    runs-on: windows
    
    steps:
      - name: Checkout Parent Repository
        uses: actions/checkout@v4

      - name: Checkout BuildAndTestAction Repository
        uses: actions/checkout@v4
        with:
          repository: WSS-PublicActions/Templates
          ref: main
          token: ${{ secrets.SECRET_TOKEN }}
          fetch-depth: 1

      - name: Call BuildAndTest Workflow
        uses: WSS-PublicActions/Templates/.gitea/workflows/BuildAndTest.yml@main
        with:
          solution_file_path: 'WebAppTemplate.sln'
          build_configuration: 'Release'
        env:
          GIT_AUTH_TOKEN: ${{ secrets.SECRET_TOKEN }}