name: WebAppTemplateCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: BuildAndTest
    runs-on: windows

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Checkout Private Template Repository
        run: |
          git clone https://${{ secrets.SECRET_TOKEN }}@gitea.example.com/WSS-PublicActions/Templates.git template-repo
        env:
          GIT_TERMINAL_PROMPT: 0  # Prevents interactive password prompt

      - name: Run WebAppTemplate Workflow
        run: |
          cp -r template-repo/.gitea/workflows/* .github/workflows/
          echo "WebAppTemplate copied, running locally..."