name: WebAppTemplateCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: WSS-PublicActions/Templates/.gitea/workflows/BuildAndTest.yml@main
    with:
      solution_file_path: './WebAppTemplate.sln'
      build_configuration: 'Release'
    secrets:
      SECRET_TOKEN: 'ABC'