name: WebAppTemplateCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-and-test:
    name: Call BuildAndTestAction
    uses: WSS-PublicActions/Templates/.gitea/workflows/BuildAndTest.yml@main
    with:
      solution_file_path: 'WebAppTemplate.sln'
      build_configuration: 'Release'
    secrets:
      GITEA_TOKEN: ${{ secrets.SECRET_TOKEN }}