name: WebAppTemplateCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: BuildAndTest
    runs-on: windows

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Checkout Private Template Repository
        run: |
          git clone https://${{ secrets.SECRET_TOKEN }}@git.websurfingstudios.com/WSS-PublicActions/Templates.git template-repo
        env:
          GIT_TERMINAL_PROMPT: 0  # Prevents interactive password prompt

      - name: Run Template
        uses: ./template-repo/.gitea/workflows/BuildAndTest.yaml
        with:
            solution_file_path: '.'
            build_configuration: 'Release'
        secrets:
            SECRET_TOKEN: ${{ secrets.SECRET_TOKEN