name: WebAppTemplateCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-and-test:
    name: Call BuildAndTestAction
    runs-on: windows
    
    steps:
      - name: Checkout Parent Repository
        uses: actions/checkout@v4

      - name: Run BuildAndTestAction
        uses: WSS-PublicActions/Templates/.github/workflows/BuildAndTestAction.yml
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          solution_file_path: 'WebAppTemplate.sln'
          build_configuration: 'Release'
